### ISSUE TITLE
帮个忙

### ISSUE THREAD

**Issue by Xian66-Gmail** [David-xian66/custom_script#3]
@HeimNad 帮我加个环境变量：NOTE_NAME

我忘给这个号管理员权限了，。。。服了

**Comment by HeimNad** [comment]
> @HeimNad 帮我加个环境变量：NOTE_NAME
> 
> 
> 
> 我忘给这个号管理员权限了，。。。服了

啊？咋帮啊

**Comment by HeimNad** [comment]
好了

**Comment by HeimNad** [comment]
你还是需要自己去设置添加 name 我看这是空的

**Comment by Xian66-Gmail** [comment]
@HeimNad 去把NOTE_NAME的值设置为我剪贴板name的值

**Comment by HeimNad** [comment]
直接写你不加到环境变量？

**Comment by Xian66-Gmail** [comment]
？

**Comment by Xian66-Gmail** [comment]
> 直接写你不加到环境变量？

没懂

**Comment by Xian66-Gmail** [comment]
剪贴板名字要隐藏一下，别暴露在代码里

**Comment by Xian66-Gmail** [comment]
@HeimNad

**Comment by HeimNad** [comment]
哦, 那你传的那个环境变量有啥用(

**Comment by HeimNad** [comment]
你怎么做到不在 secrets 写 name 你还要保证不暴露的( 
根本不可能啊

**Comment by David-Xian66** [comment]
?

**Comment by David-Xian66** [comment]
我就是让你把name写进secrets里啊

**Comment by David-Xian66** [comment]
我不说说了吗 我没权限

**Comment by David-Xian66** [comment]
> @HeimNad 帮我加个环境变量：NOTE_NAME
> 
> 
> 
> 我忘给这个号管理员权限了，。。。服了

你没理解着这句话啥意思吧 我代码都改完了 你去secrets添加下变量就行了

**Comment by HeimNad** [comment]
我咋去啊, 这个你的仓库

**Comment by David-Xian66** [comment]
哦 你也没权限是吧

**Comment by HeimNad** [comment]
只有 owner 可以改 setting

**Comment by David-Xian66** [comment]
这样啊
